import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar/Navbar'
import Footer from './Components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout =({ children }) => {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className='font-[Poppins] max-w-[1580px] mx-auto '>
        <Navbar />
          <div className="pt-[70px] min-h-[1000px]"> {children}</div>
          <Footer/>
        </div>
    
       </body>
    </html>
  )
}
export default RootLayout